### ISSUE TITLE
calculateBias() requires $M alias on input matrix

### ISSUE THREAD

**Issue by cm45t3r** [sbyrnes/likely.js#7]
Implicit cast fails when passing input matrix at method `calculateBias(input)`

**Failure scenario:**
```javascript
var input = [[1, 2], [3, 4]];
var bias = likely.calculateBias(input);
```

**Error message:**
```
TypeError: Object 1, 2, 3, 4 has no method 'rows'
at calculateMatrixAverage ([__dirname]/node_modules/likely/likely.js:287:26)
at Object.calculateBias ([__dirname]/node_modules/likely/likely.js:247:16)
...
```

**Way it is fixed from the user side:**
```javascript
var bias = likely.calculateBias($M(input));
```

Likely.js version: 1.0.0
Node.js version: 0.10.39

**Comment by sbyrnes** [comment]
Ah, this is a good catch. I can patch it in a few weeks unless you want to submit a pull request? =)

**Comment by cm45t3r** [comment]
Sure :+1:

**Comment by cm45t3r** [comment]
Fixed.
